# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: iqm/data_definitions/station_control/v1/task_service.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'iqm/data_definitions/station_control/v1/task_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from iqm.data_definitions.common.v1 import data_types_pb2 as iqm_dot_data__definitions_dot_common_dot_v1_dot_data__types__pb2
from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n:iqm/data_definitions/station_control/v1/task_service.proto\x12\'iqm.data_definitions.station_control.v1\x1a/iqm/data_definitions/common/v1/data_types.proto\x1a\x19google/protobuf/any.proto\"_\n\x10SweepTaskRequest\x12\x12\n\nqueue_name\x18\x01 \x01(\t\x12%\n\x07payload\x18\x02 \x01(\x0b\x32\x14.google.protobuf.Any\x12\x10\n\x08sweep_id\x18\x03 \x01(\t\"\xdc\x01\n\x14SweepResultsResponse\x12\x10\n\x08sweep_id\x18\x01 \x01(\t\x12[\n\x07results\x18\x02 \x03(\x0b\x32J.iqm.data_definitions.station_control.v1.SweepResultsResponse.ResultsEntry\x1aU\n\x0cResultsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x34\n\x05value\x18\x02 \x01(\x0b\x32%.iqm.data_definitions.common.v1.Array:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'iqm.data_definitions.station_control.v1.task_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SWEEPRESULTSRESPONSE_RESULTSENTRY']._loaded_options = None
  _globals['_SWEEPRESULTSRESPONSE_RESULTSENTRY']._serialized_options = b'8\001'
  _globals['_SWEEPTASKREQUEST']._serialized_start=179
  _globals['_SWEEPTASKREQUEST']._serialized_end=274
  _globals['_SWEEPRESULTSRESPONSE']._serialized_start=277
  _globals['_SWEEPRESULTSRESPONSE']._serialized_end=497
  _globals['_SWEEPRESULTSRESPONSE_RESULTSENTRY']._serialized_start=412
  _globals['_SWEEPRESULTSRESPONSE_RESULTSENTRY']._serialized_end=497
# @@protoc_insertion_point(module_scope)
